channels:
  - conda-forge
dependencies:
  - python=3.9
  - napari[all]
  - qgis=3.18
  - websockify
  - pip
  - pip:
      - jupyter-desktop-server
      - napari-segment-blobs-and-things-with-membranes
