channels:
  - conda-forge
dependencies:
  - python=3.9
  - qgis=3.18
  - websockify
  - pip
  - pip:
      - napari[all]
      - jupyter-desktop-server
      #- napari-segment-blobs-and-things-with-membranes
